# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bitcounter/bitcounter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter || ORIG_REF_NAME==bitcounter} -quiet] -quiet

# IP: bd/bitcounter/ip/bitcounter_processing_system7_0_0/bitcounter_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter_processing_system7_0_0 || ORIG_REF_NAME==bitcounter_processing_system7_0_0} -quiet] -quiet

# IP: bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter_axi_dma_0_0 || ORIG_REF_NAME==bitcounter_axi_dma_0_0} -quiet] -quiet

# IP: bd/bitcounter/ip/bitcounter_ps7_0_axi_periph_0/bitcounter_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter_ps7_0_axi_periph_0 || ORIG_REF_NAME==bitcounter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bitcounter/ip/bitcounter_rst_ps7_0_100M_0/bitcounter_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter_rst_ps7_0_100M_0 || ORIG_REF_NAME==bitcounter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/bitcounter/ip/bitcounter_xbar_0/bitcounter_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter_xbar_0 || ORIG_REF_NAME==bitcounter_xbar_0} -quiet] -quiet

# IP: bd/bitcounter/ip/bitcounter_axi_smc_0/bitcounter_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter_axi_smc_0 || ORIG_REF_NAME==bitcounter_axi_smc_0} -quiet] -quiet

# IP: bd/bitcounter/ip/bitcounter_AXI_bitcount_0_0/bitcounter_AXI_bitcount_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter_AXI_bitcount_0_0 || ORIG_REF_NAME==bitcounter_AXI_bitcount_0_0} -quiet] -quiet

# IP: bd/bitcounter/ip/bitcounter_auto_pc_0/bitcounter_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitcounter_auto_pc_0 || ORIG_REF_NAME==bitcounter_auto_pc_0} -quiet] -quiet

# XDC: bd/bitcounter/bitcounter_ooc.xdc
