# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bitcounter_axi_smc_0.xci
# IP: The module: 'bitcounter_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/bd_9aac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_0/bd_9aac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_1/bd_9aac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_2/bd_9aac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_3/bd_9aac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_4/bd_9aac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_5/bd_9aac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_6/bd_9aac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_7/bd_9aac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_8/bd_9aac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_9/bd_9aac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_1/bd_9aac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_1/bd_9aac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_5/bd_9aac_s00a2s_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_6/bd_9aac_sarn_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_7/bd_9aac_srn_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_8/bd_9aac_m00s2a_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bitcounter_axi_smc_0.xci
# IP: The module: 'bitcounter_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/bd_9aac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_0/bd_9aac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_1/bd_9aac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_2/bd_9aac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_3/bd_9aac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_4/bd_9aac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_5/bd_9aac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_6/bd_9aac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_7/bd_9aac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_8/bd_9aac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_9/bd_9aac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_1/bd_9aac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_1/bd_9aac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_5/bd_9aac_s00a2s_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_6/bd_9aac_sarn_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_7/bd_9aac_srn_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/bd_0/ip/ip_8/bd_9aac_m00s2a_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
