# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/sp20work/E315/project_2.tar/project_2/project_2.srcs/sources_1/bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0.xci
# IP: The module: 'mult_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sp20work/E315/project_2.tar/project_2/project_2.srcs/sources_1/bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/sp20work/E315/project_2.tar/project_2/project_2.srcs/sources_1/bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/sp20work/E315/project_2.tar/project_2/project_2.srcs/sources_1/bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/sp20work/E315/project_2.tar/project_2/project_2.srcs/sources_1/bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0.xci
# IP: The module: 'mult_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sp20work/E315/project_2.tar/project_2/project_2.srcs/sources_1/bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/sp20work/E315/project_2.tar/project_2/project_2.srcs/sources_1/bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/sp20work/E315/project_2.tar/project_2/project_2.srcs/sources_1/bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
