# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ema_bd/ema_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ema_bd || ORIG_REF_NAME==ema_bd} -quiet] -quiet

# IP: bd/ema_bd/ip/ema_bd_ema_ip_0_0/ema_bd_ema_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ema_bd_ema_ip_0_0 || ORIG_REF_NAME==ema_bd_ema_ip_0_0} -quiet] -quiet

# IP: bd/ema_bd/ip/ema_bd_processing_system7_0_0/ema_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ema_bd_processing_system7_0_0 || ORIG_REF_NAME==ema_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/ema_bd/ip/ema_bd_ps7_0_axi_periph_0/ema_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ema_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==ema_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ema_bd/ip/ema_bd_rst_ps7_0_100M_0/ema_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ema_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==ema_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ema_bd/ip/ema_bd_auto_pc_0/ema_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ema_bd_auto_pc_0 || ORIG_REF_NAME==ema_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/ema_bd/ema_bd_ooc.xdc
