# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0.xci
# IP: The module: 'bitcounter_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0.xci
# IP: The module: 'bitcounter_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_axi_dma_0_0/bitcounter_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
