# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/led_blink/led_blink.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_blink || ORIG_REF_NAME==led_blink} -quiet] -quiet

# IP: bd/led_blink/ip/led_blink_processing_system7_0_0/led_blink_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_blink_processing_system7_0_0 || ORIG_REF_NAME==led_blink_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_blink/ip/led_blink_axi_gpio_0_0/led_blink_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_blink_axi_gpio_0_0 || ORIG_REF_NAME==led_blink_axi_gpio_0_0} -quiet] -quiet

# IP: bd/led_blink/ip/led_blink_ps7_0_axi_periph_1/led_blink_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_blink_ps7_0_axi_periph_1 || ORIG_REF_NAME==led_blink_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/led_blink/ip/led_blink_rst_ps7_0_100M_1/led_blink_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_blink_rst_ps7_0_100M_1 || ORIG_REF_NAME==led_blink_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/led_blink/ip/led_blink_auto_pc_0/led_blink_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_blink_auto_pc_0 || ORIG_REF_NAME==led_blink_auto_pc_0} -quiet] -quiet

# XDC: bd/led_blink/led_blink_ooc.xdc
