# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bitflip_system_ila_0_1.xci
# IP: The module: 'bitflip_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/bd_37ab.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_37ab || ORIG_REF_NAME==bd_37ab} -quiet] -quiet

# IP: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/bd_37ab_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_37ab_ila_lib_0 || ORIG_REF_NAME==bd_37ab_ila_lib_0} -quiet] -quiet

# IP: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_1/bd_37ab_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_37ab_g_inst_0 || ORIG_REF_NAME==bd_37ab_g_inst_0} -quiet] -quiet

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_37ab_ila_lib_0 || ORIG_REF_NAME==bd_37ab_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_37ab_ila_lib_0 || ORIG_REF_NAME==bd_37ab_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/bd_37ab_ila_lib_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/bd_37ab_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bitflip_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitflip_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bitflip_system_ila_0_1.xci
# IP: The module: 'bitflip_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/bd_37ab.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_37ab || ORIG_REF_NAME==bd_37ab} -quiet] -quiet

# IP: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/bd_37ab_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_37ab_ila_lib_0 || ORIG_REF_NAME==bd_37ab_ila_lib_0} -quiet] -quiet

# IP: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_1/bd_37ab_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_37ab_g_inst_0 || ORIG_REF_NAME==bd_37ab_g_inst_0} -quiet] -quiet

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_37ab_ila_lib_0 || ORIG_REF_NAME==bd_37ab_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_37ab_ila_lib_0 || ORIG_REF_NAME==bd_37ab_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/bd_37ab_ila_lib_0_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/bd_37ab_ooc.xdc

# XDC: /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bitflip_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitflip_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
