# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mult/mult.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult || ORIG_REF_NAME==mult} -quiet] -quiet

# IP: bd/mult/ip/mult_AXI_mult_0_0/mult_AXI_mult_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_AXI_mult_0_0 || ORIG_REF_NAME==mult_AXI_mult_0_0} -quiet] -quiet

# IP: bd/mult/ip/mult_processing_system7_0_0/mult_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_processing_system7_0_0 || ORIG_REF_NAME==mult_processing_system7_0_0} -quiet] -quiet

# IP: bd/mult/ip/mult_ps7_0_axi_periph_0/mult_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_ps7_0_axi_periph_0 || ORIG_REF_NAME==mult_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/mult/ip/mult_rst_ps7_0_100M_0/mult_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_rst_ps7_0_100M_0 || ORIG_REF_NAME==mult_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/mult/ip/mult_auto_pc_0/mult_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_auto_pc_0 || ORIG_REF_NAME==mult_auto_pc_0} -quiet] -quiet

# XDC: bd/mult/mult_ooc.xdc
