# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ejapundz/fa19-research/E315/bitflip/bitflip.cache/wt [current_project]
set_property parent.project_path /home/ejapundz/fa19-research/E315/bitflip/bitflip.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_output_repo /home/ejapundz/fa19-research/E315/bitflip/bitflip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/hdl/bitflip_wrapper.v
add_files /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/bitflip.bd
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_processing_system7_0_0/bitflip_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_rst_ps7_0_100M_0/bitflip_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_rst_ps7_0_100M_0/bitflip_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_rst_ps7_0_100M_0/bitflip_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_1/bd_2566_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_1/bd_2566_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_2/bd_2566_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_3/bd_2566_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_4/bd_2566_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_5/bd_2566_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_6/bd_2566_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_10/bd_2566_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_11/bd_2566_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_12/bd_2566_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_16/bd_2566_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_17/bd_2566_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_18/bd_2566_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_19/bd_2566_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_20/bd_2566_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_21/bd_2566_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_22/bd_2566_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_23/bd_2566_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_24/bd_2566_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_smc_0/bd_0/ip/ip_25/bd_2566_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_xbar_0/bitflip_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/ip/ip_0/bd_37ab_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bd_0/bd_37ab_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_system_ila_0_1/bitflip_system_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_auto_pc_0/bitflip_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ejapundz/fa19-research/E315/bitflip/bitflip.srcs/sources_1/bd/bitflip/bitflip_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top bitflip_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bitflip_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bitflip_wrapper_utilization_synth.rpt -pb bitflip_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
