# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bitflip/bitflip.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip || ORIG_REF_NAME==bitflip} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_processing_system7_0_0/bitflip_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_processing_system7_0_0 || ORIG_REF_NAME==bitflip_processing_system7_0_0} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_axi_dma_0_0 || ORIG_REF_NAME==bitflip_axi_dma_0_0} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_ps7_0_axi_periph_0/bitflip_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_ps7_0_axi_periph_0 || ORIG_REF_NAME==bitflip_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_rst_ps7_0_100M_0/bitflip_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_rst_ps7_0_100M_0 || ORIG_REF_NAME==bitflip_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_axi_smc_0/bitflip_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_axi_smc_0 || ORIG_REF_NAME==bitflip_axi_smc_0} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_xbar_0/bitflip_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_xbar_0 || ORIG_REF_NAME==bitflip_xbar_0} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_bit_flip_0_2/bitflip_bit_flip_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_bit_flip_0_2 || ORIG_REF_NAME==bitflip_bit_flip_0_2} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_system_ila_0_1/bitflip_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_system_ila_0_1 || ORIG_REF_NAME==bitflip_system_ila_0_1} -quiet] -quiet

# IP: bd/bitflip/ip/bitflip_auto_pc_0/bitflip_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitflip_auto_pc_0 || ORIG_REF_NAME==bitflip_auto_pc_0} -quiet] -quiet

# XDC: bd/bitflip/bitflip_ooc.xdc
