# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ejapundz/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0.xci
# IP: The module: 'bitflip_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ejapundz/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitflip_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/ejapundz/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitflip_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/ejapundz/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitflip_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ejapundz/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0.xci
# IP: The module: 'bitflip_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ejapundz/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitflip_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/ejapundz/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitflip_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/ejapundz/bitflip/bitflip.srcs/sources_1/bd/bitflip/ip/bitflip_axi_dma_0_0/bitflip_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitflip_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
