# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_processing_system7_0_0/bitcounter_processing_system7_0_0.xci
# IP: The module: 'bitcounter_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_processing_system7_0_0/bitcounter_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_processing_system7_0_0/bitcounter_processing_system7_0_0.xci
# IP: The module: 'bitcounter_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ejapundz/fa19-research/E315/project_4/project_4.srcs/sources_1/bd/bitcounter/ip/bitcounter_processing_system7_0_0/bitcounter_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitcounter_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
