webtalk_init -webtalk_dir /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_2.tar/project_2/project_2.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-02-05 20:31:20" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "207618128_1777510348_210665627_004" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "o8a7ujsfi09kk02m0hddu4qmf7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseWorkstation" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Workstation release 7.7 (Maipo)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1981.384 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.439 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1580942498000" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1580942498000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1580952680083"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1580952680083"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1580952680083"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1580952680083"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1580952680083"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1580952680083"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1580952680083"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1580952680083"
webtalk_transmit -clientid 725344219 -regid "207618128_1777510348_210665627_004" -xml /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_2.tar/project_2/project_2.sdk/webtalk/usage_statistics_ext_sdk.xml -html /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_2.tar/project_2/project_2.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /nfs/nfs7/home/ejapundz/sp20-e315/E315/project_2.tar/project_2/project_2.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
